SET IDENTITY_INSERT [dbo].[influencerNames] ON
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (1, N'MrBeast')
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (2, N'PewDiePie')
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (3, N'Like Nastya')
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (4, N'Vlad and Niki')
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (5, N'Blackpink')
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (6, N'BANGTANTV')
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (7, N'Justin Bieber')
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (8, N'Dude Perfect')
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (9, N'Marshmello')
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (10, N'EminemMusic')
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (11, N'Ed Sheeran')
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (12, N'Ariana Grande')
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (13, N'Taylor Swift')
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (14, N'Billie Eilish')
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (15, N'JuegaGerman')
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (16, N'Fernanfloo')
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (17, N'Felipe Neto')
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (18, N'Bad Bunny')
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (19, N'whinderssonnunes')
INSERT INTO [dbo].[influencerNames] ([Id], [Name]) VALUES (20, N'Você Sabia?')
SET IDENTITY_INSERT [dbo].[influencerNames] OFF
