SET IDENTITY_INSERT [dbo].[Influencer] ON
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (41, N'Felipe Neto', NULL, N' Brazil')
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (42, N'whinderssonnunes', NULL, N' Brazil')
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (43, N'Você Sabia?', NULL, N' Brazil')
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (44, N'Justin Bieber', NULL, N' Canada')
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (45, N'JuegaGerman', NULL, N' Chile')
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (46, N'Fernanfloo', NULL, N' El Salvador')
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (47, N'Bad Bunny', NULL, N' Puerto Rico')
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (48, N'Vlad and Niki', NULL, N' Russia')
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (49, N'Blackpink', NULL, N' South Korea')
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (50, N'BANGTANTV', NULL, N' South Korea')
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (51, N'PewDiePie', NULL, N' Sweden')
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (52, N'Ed Sheeran', NULL, N' United Kingdom')
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (53, N'MrBeast', NULL, N' United States')
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (54, N'Like Nastya', NULL, N' United States')
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (55, N'Dude Perfect', NULL, N' United States')
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (56, N'Marshmello', NULL, N' United States')
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (57, N'EminemMusic', NULL, N' United States')
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (58, N'Ariana Grande', NULL, N' United States')
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (59, N'Taylor Swift', NULL, N' United States')
INSERT INTO [dbo].[Influencer] ([Id], [Name], [City], [Country]) VALUES (60, N'Billie Eilish', NULL, N' United States')
SET IDENTITY_INSERT [dbo].[Influencer] OFF
